# Generated by Django 4.0.3 on 2022-04-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.TextField(blank=True, null=True)),
                ('player', models.TextField(blank=True, max_length=20, null=True)),
                ('game_id', models.TextField(blank=True, null=True)),
                ('game', models.TextField(blank=True, max_length=20, null=True)),
                ('place', models.TextField(blank=True, null=True)),
                ('played', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
