# Generated by Django 4.0.3 on 2022-04-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rankingsmodel_delete_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingsmodel',
            name='game',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rankingsmodel',
            name='game_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingsmodel',
            name='place',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingsmodel',
            name='player',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rankingsmodel',
            name='player_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
