# Generated by Django 4.0.3 on 2022-04-02 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rankingsmodel_game_session_rankingsmodel_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgamesmodel',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='playersmodel',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='rankingsmodel',
            name='session_id',
        ),
    ]
