# Generated by Django 4.0.3 on 2022-04-03 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_boardgamesmodel_game_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardgamesmodel',
            old_name='game',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='playersmodel',
            old_name='player',
            new_name='name',
        ),
    ]
