# Generated by Django 4.0.3 on 2022-04-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_game_boardgamesmodel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankingsmodel',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='rankingsmodel',
            name='player_id',
        ),
    ]
