# Generated by Django 4.0.3 on 2022-04-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_rankingsmodel_game_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingsmodel',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
