# Generated by Django 4.0.3 on 2022-04-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rankingsmodel_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingsmodel',
            name='number_of_players',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
